name: Build and create a release from new tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use default Node.js version
        uses: actions/setup-node@v3

      - name: Install yarn dependencies
        run: |
          cd ${GITHUB_WORKSPACE} && yarn --frozen-lockfile
        
      - name: Build packages
        run: |
          cd ${GITHUB_WORKSPACE} && yarn build

      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}